# Generated by Django 5.2.4 on 2025-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=1)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('membership_type', models.CharField(max_length=100)),
            ],
        ),
    ]
