# Generated by Django 5.2.4 on 2025-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic'), ('vip', 'VIP')], max_length=10),
        ),
    ]
